environment: "Comming from UAT"
customer:
       accounts: "SBI, ICICI, HDFC"
       firstname: "Achu"
       lastname: "Pattnaik"
       dbValues:
               "{dbConnection : 'http://111.111', dbPort: '3030', dbUser: 'Achu'}"

management:endpoints.web.exposure.include : "*"
