environment: "Comming from UAT"
customer:
       accounts: "SBI, ICICI, HDFC"
       firstname: "Achu"
       lastname: "Pattnaik"
       dbValues:
               "{dbConnection : 'http://192.168.52.111', dbPort: '9999', dbUser: 'Achu'}"

management:endpoints.web.exposure.include : "*"
